name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build
        run: |
          echo "Aqui você coloca seu comando de build, se precisar"
          # Ex: npm run build (se for React, por exemplo)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./caminho/da/sua/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

